<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "social_publisher"
 *
 * Auto generated by Extension Builder 2016-06-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Social Publisher',
	'description' => 'Publish contents to social media ',
	'category' => 'plugin',
	'author' => 'Siju E Raju',
	'author_email' => 'siju.er@pitsolutions.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);